// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://narxerpbhbqpeeaaikgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcnhlcnBiaGJxcGVlYWFpa2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDMwMTIsImV4cCI6MjA1OTE3OTAxMn0.2pkg-5d5MENTMnPpZNLZz31c1BFsbQEJHPzX-NKbRBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);